### PR TITLE
fix(request): Set GET as default request method

### LINKED ISSUE #49: Query parameter time_filter ignored
## Current Behavior

When making a request to: `/users/me/orders/?time_filter=current_future` via the SDK I am receiving _all_ the orders back regardless of the time_filter used

## Expected Behavior

I expect to receive only the `current_future` or `past` events depending on the parameter I provide

## Steps to Reproduce (for bugs)
Generate a token
Provide a request to: `/users/me/orders/?time_filter=current_future`
Observe the orders returned

Provide a request to: `/users/me/orders/?time_filter=past`
Observe the same orders are returned

I then used Insomnia (API client) to make the same request (same token etc) and observed properly filtered events returned depending on the query parameter provided. 

## Your Environment

* SDK version: 1.0.3
* Node version: 8.11.4
* Browser name and version: Chrome 
* Operating system: Mac OS, El Capitan

### PR DESCRIPTION
**Pull request by kwelch**
## Description
As mentioned in #49, query params were being ignored when passed in via the SDK. 

I investigated and found that this was due to our default of the `Content-Type` header. The defaulting was put in place to handle `POST` but since method is undefined it was also being set for implied `GET` requests. 

## How Has This Been Tested?
Tests have been updated. I also verified that setting get will address query params not being parsed properly on the backend. 

## Checklist:

*   [x] I have read the [**CONTRIBUTING** document](https://github.com/eventbrite/eventbrite-sdk-javascript/blob/master/CONTRIBUTING.md).
*   [x] I have updated the documentation accordingly.
*   [x] I have added tests to cover my changes.
*   [x] I have run `yarn validate` to ensure that tests, typescript and linting are all in order.

resolves #49

### CODE REVIEW

File: src/request.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ const _tryParseJSON = (res: Response): Promise<any> => {
  */
 export const _fetchJSON = (
     url: string,
-    {headers, method, mode, ...options}: RequestInit = {}
+    {headers = {}, method = 'GET', mode, ...options}: RequestInit = {}
```
Comment (kwelch-eb) [inline src/request.ts]: Another way to accomplish this would be to update the if below to match how we do it internally. 

`if (method && method !== 'GET') {`

Comment (benmvp) [reply src/request.ts]: Probably should go with the other way. Otherwise a lot of internal code would break.

Comment (kwelch-eb) [reply src/request.ts]: Internally, we also default it, but we do it later in this function. I would imagine the internal function was written pre-es6 defaults

**Comment by kwelch** [comment]
Are we good to merge this?

**Comment by kwelch-eb** [comment]
Sounds good I will bump in core in the AM.
